-- ============================================================================
-- SCRIPT DE INSTALACIÓN COMPLETA - SISTEMA INMOBILIARIO
-- ============================================================================
-- Base de datos: Oracle
-- Usuario: INMO
-- Password: inmo123
-- ============================================================================
-- INSTRUCCIONES:
-- 1. Conectarse como SYSTEM o usuario con privilegios DBA
-- 2. Ejecutar este script completo
-- 3. El usuario INMO será creado automáticamente
-- ============================================================================

-- ============================================================================
-- PASO 1: CREAR USUARIO INMO (SI NO EXISTE)
-- ============================================================================

-- Intentar eliminar el usuario si existe (ignorar error si no existe)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER INMO CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN -- -1918 = usuario no existe
            RAISE;
        END IF;
END;
/

-- Crear el usuario INMO
CREATE USER INMO IDENTIFIED BY inmo123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

-- Otorgar permisos necesarios
GRANT CONNECT, RESOURCE TO INMO;
GRANT CREATE SESSION TO INMO;
GRANT CREATE TABLE TO INMO;
GRANT CREATE VIEW TO INMO;
GRANT CREATE SEQUENCE TO INMO;
GRANT CREATE TRIGGER TO INMO;
GRANT CREATE PROCEDURE TO INMO;

-- Conectar como usuario INMO
ALTER SESSION SET CURRENT_SCHEMA = INMO;

PROMPT ============================================================================
PROMPT Usuario INMO creado exitosamente
PROMPT ============================================================================

-- ============================================================================
-- PASO 2: ELIMINAR TABLAS SI EXISTEN (ORDEN INVERSO POR DEPENDENCIAS)
-- ============================================================================

BEGIN
    FOR rec IN (SELECT table_name FROM user_tables
                WHERE table_name IN ('CONTRAOFERTA','OFERTA','ACUERDO','INMUEBLE',
                                     'COMPRADOR','VENDEDOR','AGENTE','USUARIO'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

PROMPT ============================================================================
PROMPT Tablas anteriores eliminadas (si existían)
PROMPT ============================================================================

-- ============================================================================
-- PASO 3: CREAR TODAS LAS TABLAS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLA: USUARIO
-- ----------------------------------------------------------------------------
CREATE TABLE USUARIO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    EMAIL VARCHAR2(120) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(120) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    ROL VARCHAR2(30) NOT NULL CHECK (ROL IN ('ADMIN', 'AGENTE', 'VENDEDOR', 'COMPRADOR')),
    ACTIVO CHAR(1) DEFAULT 'S' NOT NULL CHECK (ACTIVO IN ('S', 'N')),
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP
);

COMMENT ON TABLE USUARIO IS 'Usuarios del sistema con autenticación';
COMMENT ON COLUMN USUARIO.ROL IS 'Roles: ADMIN, AGENTE, VENDEDOR, COMPRADOR';
COMMENT ON COLUMN USUARIO.PASSWORD_HASH IS 'Hash SHA-256 de la contraseña';

PROMPT - Tabla USUARIO creada

-- ----------------------------------------------------------------------------
-- TABLA: AGENTE
-- ----------------------------------------------------------------------------
CREATE TABLE AGENTE (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USUARIO_ID NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(30),
    EMAIL VARCHAR2(120) NOT NULL UNIQUE,
    DIRECCION VARCHAR2(200),
    ANTIGUEDAD_EMPRESA NUMBER(3) DEFAULT 0,
    CANTIDAD_VENDIDOS NUMBER(5) DEFAULT 0,
    ACTIVO CHAR(1) DEFAULT 'S' NOT NULL CHECK (ACTIVO IN ('S', 'N')),
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_AGENTE_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID) ON DELETE SET NULL
);

COMMENT ON TABLE AGENTE IS 'Agentes inmobiliarios';
COMMENT ON COLUMN AGENTE.ANTIGUEDAD_EMPRESA IS 'Antigüedad en años';
COMMENT ON COLUMN AGENTE.CANTIDAD_VENDIDOS IS 'Total de inmuebles vendidos';

CREATE INDEX IDX_AGENTE_EMAIL ON AGENTE(EMAIL);
CREATE INDEX IDX_AGENTE_USUARIO ON AGENTE(USUARIO_ID);

PROMPT - Tabla AGENTE creada

-- ----------------------------------------------------------------------------
-- TABLA: VENDEDOR
-- ----------------------------------------------------------------------------
CREATE TABLE VENDEDOR (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USUARIO_ID NUMBER,
    AGENTE_ID NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(120),
    TELEFONO VARCHAR2(30),
    DIRECCION VARCHAR2(200),
    ACTIVO CHAR(1) DEFAULT 'S' NOT NULL CHECK (ACTIVO IN ('S', 'N')),
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_VENDEDOR_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID) ON DELETE SET NULL,
    CONSTRAINT FK_VENDEDOR_AGENTE FOREIGN KEY (AGENTE_ID)
        REFERENCES AGENTE(ID) ON DELETE SET NULL
);

COMMENT ON TABLE VENDEDOR IS 'Vendedores de inmuebles';

CREATE INDEX IDX_VENDEDOR_AGENTE ON VENDEDOR(AGENTE_ID);
CREATE INDEX IDX_VENDEDOR_USUARIO ON VENDEDOR(USUARIO_ID);

PROMPT - Tabla VENDEDOR creada

-- ----------------------------------------------------------------------------
-- TABLA: COMPRADOR
-- ----------------------------------------------------------------------------
CREATE TABLE COMPRADOR (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    USUARIO_ID NUMBER,
    AGENTE_ID NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(200),
    TELEFONO VARCHAR2(30),
    ESTADO_CIVIL VARCHAR2(30) CHECK (ESTADO_CIVIL IN ('SOLTERO', 'CASADO', 'DIVORCIADO', 'VIUDO')),
    NACIONALIDAD VARCHAR2(50),
    EDAD NUMBER(3) CHECK (EDAD >= 18 AND EDAD <= 120),
    EMAIL VARCHAR2(120),
    ACTIVO CHAR(1) DEFAULT 'S' NOT NULL CHECK (ACTIVO IN ('S', 'N')),
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_COMPRADOR_USUARIO FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID) ON DELETE SET NULL,
    CONSTRAINT FK_COMPRADOR_AGENTE FOREIGN KEY (AGENTE_ID)
        REFERENCES AGENTE(ID) ON DELETE SET NULL
);

COMMENT ON TABLE COMPRADOR IS 'Compradores de inmuebles';

CREATE INDEX IDX_COMPRADOR_AGENTE ON COMPRADOR(AGENTE_ID);
CREATE INDEX IDX_COMPRADOR_USUARIO ON COMPRADOR(USUARIO_ID);

PROMPT - Tabla COMPRADOR creada

-- ----------------------------------------------------------------------------
-- TABLA: INMUEBLE
-- ----------------------------------------------------------------------------
CREATE TABLE INMUEBLE (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    VENDEDOR_ID NUMBER NOT NULL,
    AGENTE_ID NUMBER,
    DIRECCION VARCHAR2(200) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL CHECK (TIPO IN ('CASA', 'DEPARTAMENTO', 'TERRENO', 'LOCAL', 'OFICINA')),
    PRECIO NUMBER(15,2) NOT NULL CHECK (PRECIO > 0),
    METRAJE NUMBER(10,2) CHECK (METRAJE > 0),
    ANTIGUEDAD NUMBER(4),
    MODELO VARCHAR2(100),
    MATERIAL VARCHAR2(100),
    CONDICION VARCHAR2(50) CHECK (CONDICION IN ('NUEVO', 'SEMI_NUEVO', 'USADO', 'REMODELADO')),
    HABITACIONES NUMBER(2),
    BANOS NUMBER(2),
    ESTACIONAMIENTOS NUMBER(2),
    DESCRIPCION VARCHAR2(1000),
    ESTADO VARCHAR2(30) DEFAULT 'DISPONIBLE'
        CHECK (ESTADO IN ('DISPONIBLE', 'EN_NEGOCIACION', 'VENDIDO', 'RETIRADO')),
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_INMUEBLE_VENDEDOR FOREIGN KEY (VENDEDOR_ID)
        REFERENCES VENDEDOR(ID) ON DELETE CASCADE,
    CONSTRAINT FK_INMUEBLE_AGENTE FOREIGN KEY (AGENTE_ID)
        REFERENCES AGENTE(ID) ON DELETE SET NULL
);

COMMENT ON TABLE INMUEBLE IS 'Inmuebles en venta';
COMMENT ON COLUMN INMUEBLE.METRAJE IS 'Metros cuadrados';
COMMENT ON COLUMN INMUEBLE.ANTIGUEDAD IS 'Antigüedad en años';

CREATE INDEX IDX_INMUEBLE_VENDEDOR ON INMUEBLE(VENDEDOR_ID);
CREATE INDEX IDX_INMUEBLE_AGENTE ON INMUEBLE(AGENTE_ID);
CREATE INDEX IDX_INMUEBLE_TIPO ON INMUEBLE(TIPO);
CREATE INDEX IDX_INMUEBLE_ESTADO ON INMUEBLE(ESTADO);
CREATE INDEX IDX_INMUEBLE_PRECIO ON INMUEBLE(PRECIO);

PROMPT - Tabla INMUEBLE creada

-- ----------------------------------------------------------------------------
-- TABLA: OFERTA
-- ----------------------------------------------------------------------------
CREATE TABLE OFERTA (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    INMUEBLE_ID NUMBER NOT NULL,
    COMPRADOR_ID NUMBER NOT NULL,
    AGENTE_ID NUMBER,
    MONTO NUMBER(15,2) NOT NULL CHECK (MONTO > 0),
    FORMA_PAGO VARCHAR2(50) CHECK (FORMA_PAGO IN ('EFECTIVO', 'FINANCIAMIENTO', 'MIXTO', 'CREDITO')),
    TIEMPO_PAGO NUMBER(3),
    ESTADO VARCHAR2(30) DEFAULT 'PENDIENTE'
        CHECK (ESTADO IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CONTRAOFERTADA', 'CANCELADA')),
    PRIORIDAD NUMBER(2) DEFAULT 5,
    COMENTARIOS VARCHAR2(500),
    FECHA_OFERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_RESPUESTA TIMESTAMP,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_OFERTA_INMUEBLE FOREIGN KEY (INMUEBLE_ID)
        REFERENCES INMUEBLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_OFERTA_COMPRADOR FOREIGN KEY (COMPRADOR_ID)
        REFERENCES COMPRADOR(ID) ON DELETE CASCADE,
    CONSTRAINT FK_OFERTA_AGENTE FOREIGN KEY (AGENTE_ID)
        REFERENCES AGENTE(ID) ON DELETE SET NULL
);

COMMENT ON TABLE OFERTA IS 'Ofertas de compra realizadas por compradores';
COMMENT ON COLUMN OFERTA.TIEMPO_PAGO IS 'Tiempo de pago en meses';
COMMENT ON COLUMN OFERTA.PRIORIDAD IS '1=Mayor prioridad (efectivo, menor tiempo), 10=Menor';

CREATE INDEX IDX_OFERTA_INMUEBLE ON OFERTA(INMUEBLE_ID);
CREATE INDEX IDX_OFERTA_COMPRADOR ON OFERTA(COMPRADOR_ID);
CREATE INDEX IDX_OFERTA_ESTADO ON OFERTA(ESTADO);
CREATE INDEX IDX_OFERTA_FECHA ON OFERTA(FECHA_OFERTA);
CREATE INDEX IDX_OFERTA_PRIORIDAD ON OFERTA(PRIORIDAD);

PROMPT - Tabla OFERTA creada

-- ----------------------------------------------------------------------------
-- TABLA: CONTRAOFERTA
-- ----------------------------------------------------------------------------
CREATE TABLE CONTRAOFERTA (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    OFERTA_ID NUMBER NOT NULL,
    VENDEDOR_ID NUMBER NOT NULL,
    MONTO NUMBER(15,2) NOT NULL CHECK (MONTO > 0),
    FORMA_PAGO VARCHAR2(50) CHECK (FORMA_PAGO IN ('EFECTIVO', 'FINANCIAMIENTO', 'MIXTO', 'CREDITO')),
    TIEMPO_PAGO NUMBER(3),
    ESTADO VARCHAR2(30) DEFAULT 'PENDIENTE'
        CHECK (ESTADO IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA')),
    COMENTARIOS VARCHAR2(500),
    FECHA_CONTRAOFERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_RESPUESTA TIMESTAMP,
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_CONTRAOFERTA_OFERTA FOREIGN KEY (OFERTA_ID)
        REFERENCES OFERTA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CONTRAOFERTA_VENDEDOR FOREIGN KEY (VENDEDOR_ID)
        REFERENCES VENDEDOR(ID) ON DELETE CASCADE
);

COMMENT ON TABLE CONTRAOFERTA IS 'Contraofertas de vendedores sobre ofertas de compra';

CREATE INDEX IDX_CONTRAOFERTA_OFERTA ON CONTRAOFERTA(OFERTA_ID);
CREATE INDEX IDX_CONTRAOFERTA_VENDEDOR ON CONTRAOFERTA(VENDEDOR_ID);

PROMPT - Tabla CONTRAOFERTA creada

-- ----------------------------------------------------------------------------
-- TABLA: ACUERDO
-- ----------------------------------------------------------------------------
CREATE TABLE ACUERDO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    INMUEBLE_ID NUMBER NOT NULL,
    COMPRADOR_ID NUMBER NOT NULL,
    VENDEDOR_ID NUMBER NOT NULL,
    AGENTE_ID NUMBER,
    OFERTA_ID NUMBER,
    MONTO_FINAL NUMBER(15,2) NOT NULL CHECK (MONTO_FINAL > 0),
    FORMA_PAGO VARCHAR2(50),
    TIEMPO_PAGO NUMBER(3),
    ESTADO VARCHAR2(30) DEFAULT 'PENDIENTE'
        CHECK (ESTADO IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO')),
    FECHA_ACUERDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_CIERRE TIMESTAMP,
    NOTAS VARCHAR2(1000),
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO_EN TIMESTAMP,
    CONSTRAINT FK_ACUERDO_INMUEBLE FOREIGN KEY (INMUEBLE_ID)
        REFERENCES INMUEBLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACUERDO_COMPRADOR FOREIGN KEY (COMPRADOR_ID)
        REFERENCES COMPRADOR(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACUERDO_VENDEDOR FOREIGN KEY (VENDEDOR_ID)
        REFERENCES VENDEDOR(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACUERDO_AGENTE FOREIGN KEY (AGENTE_ID)
        REFERENCES AGENTE(ID) ON DELETE SET NULL,
    CONSTRAINT FK_ACUERDO_OFERTA FOREIGN KEY (OFERTA_ID)
        REFERENCES OFERTA(ID) ON DELETE SET NULL
);

COMMENT ON TABLE ACUERDO IS 'Acuerdos de compra-venta finalizados';

CREATE INDEX IDX_ACUERDO_INMUEBLE ON ACUERDO(INMUEBLE_ID);
CREATE INDEX IDX_ACUERDO_COMPRADOR ON ACUERDO(COMPRADOR_ID);
CREATE INDEX IDX_ACUERDO_VENDEDOR ON ACUERDO(VENDEDOR_ID);
CREATE INDEX IDX_ACUERDO_AGENTE ON ACUERDO(AGENTE_ID);
CREATE INDEX IDX_ACUERDO_FECHA ON ACUERDO(FECHA_ACUERDO);

PROMPT - Tabla ACUERDO creada

PROMPT ============================================================================
PROMPT Todas las tablas creadas exitosamente
PROMPT ============================================================================

-- ============================================================================
-- PASO 4: CREAR TRIGGERS
-- ============================================================================

-- Triggers de auditoría (actualización de fechas)
CREATE OR REPLACE TRIGGER TRG_USUARIO_UPD
BEFORE UPDATE ON USUARIO FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_AGENTE_UPD
BEFORE UPDATE ON AGENTE FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_VENDEDOR_UPD
BEFORE UPDATE ON VENDEDOR FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_COMPRADOR_UPD
BEFORE UPDATE ON COMPRADOR FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_INMUEBLE_UPD
BEFORE UPDATE ON INMUEBLE FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_OFERTA_UPD
BEFORE UPDATE ON OFERTA FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONTRAOFERTA_UPD
BEFORE UPDATE ON CONTRAOFERTA FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ACUERDO_UPD
BEFORE UPDATE ON ACUERDO FOR EACH ROW
BEGIN
    :NEW.ACTUALIZADO_EN := CURRENT_TIMESTAMP;
END;
/

PROMPT - Triggers de auditoría creados

-- Trigger para calcular prioridad de oferta
CREATE OR REPLACE TRIGGER TRG_OFERTA_PRIORIDAD
BEFORE INSERT OR UPDATE ON OFERTA
FOR EACH ROW
DECLARE
    v_prioridad NUMBER := 5;
BEGIN
    -- Calcular prioridad base
    v_prioridad := 10;

    -- Si es efectivo, mayor prioridad
    IF :NEW.FORMA_PAGO = 'EFECTIVO' THEN
        v_prioridad := v_prioridad - 4;
    ELSIF :NEW.FORMA_PAGO = 'MIXTO' THEN
        v_prioridad := v_prioridad - 2;
    END IF;

    -- Si el tiempo es menor, mayor prioridad
    IF :NEW.TIEMPO_PAGO IS NOT NULL THEN
        IF :NEW.TIEMPO_PAGO <= 1 THEN
            v_prioridad := v_prioridad - 3;
        ELSIF :NEW.TIEMPO_PAGO <= 6 THEN
            v_prioridad := v_prioridad - 2;
        ELSIF :NEW.TIEMPO_PAGO <= 12 THEN
            v_prioridad := v_prioridad - 1;
        END IF;
    END IF;

    -- Asegurar que esté en rango 1-10
    IF v_prioridad < 1 THEN
        v_prioridad := 1;
    ELSIF v_prioridad > 10 THEN
        v_prioridad := 10;
    END IF;

    :NEW.PRIORIDAD := v_prioridad;
END;
/

PROMPT - Trigger de prioridad de ofertas creado

-- Trigger para actualizar contador de inmuebles vendidos del agente
CREATE OR REPLACE TRIGGER TRG_ACUERDO_CONTADOR
AFTER INSERT OR UPDATE ON ACUERDO
FOR EACH ROW
BEGIN
    IF :NEW.ESTADO = 'COMPLETADO' AND :NEW.AGENTE_ID IS NOT NULL THEN
        -- Actualizar contador del agente
        UPDATE AGENTE
        SET CANTIDAD_VENDIDOS = CANTIDAD_VENDIDOS + 1
        WHERE ID = :NEW.AGENTE_ID;

        -- Marcar inmueble como vendido
        UPDATE INMUEBLE
        SET ESTADO = 'VENDIDO'
        WHERE ID = :NEW.INMUEBLE_ID;
    END IF;
END;
/

PROMPT - Trigger de contador de ventas creado

PROMPT ============================================================================
PROMPT Todos los triggers creados exitosamente
PROMPT ============================================================================

-- ============================================================================
-- PASO 5: INSERTAR DATOS DE PRUEBA
-- ============================================================================

-- Usuario Admin (password: 123456)
-- Hash SHA-256 de 123456: 8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92
INSERT INTO USUARIO (EMAIL, PASSWORD_HASH, NOMBRE, ROL, ACTIVO)
VALUES ('admin@inmo.test', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        'Administrador', 'ADMIN', 'S');

INSERT INTO USUARIO (EMAIL, PASSWORD_HASH, NOMBRE, ROL, ACTIVO)
VALUES ('agente1@inmo.test', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        'Juan Pérez', 'AGENTE', 'S');

INSERT INTO USUARIO (EMAIL, PASSWORD_HASH, NOMBRE, ROL, ACTIVO)
VALUES ('vendedor1@inmo.test', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        'María García', 'VENDEDOR', 'S');

INSERT INTO USUARIO (EMAIL, PASSWORD_HASH, NOMBRE, ROL, ACTIVO)
VALUES ('comprador1@inmo.test', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',
        'Carlos López', 'COMPRADOR', 'S');

PROMPT - Usuarios de prueba insertados

-- Agentes
INSERT INTO AGENTE (USUARIO_ID, NOMBRE, TELEFONO, EMAIL, DIRECCION, ANTIGUEDAD_EMPRESA, CANTIDAD_VENDIDOS)
VALUES (2, 'Juan Pérez', '5551234567', 'agente1@inmo.test', 'Av. Principal 123, Guatemala', 5, 25);

INSERT INTO AGENTE (NOMBRE, TELEFONO, EMAIL, DIRECCION, ANTIGUEDAD_EMPRESA, CANTIDAD_VENDIDOS)
VALUES ('Ana Martínez', '5559876543', 'agente2@inmo.test', 'Calle Secundaria 456, Guatemala', 3, 15);

PROMPT - Agentes insertados

-- Vendedores
INSERT INTO VENDEDOR (USUARIO_ID, AGENTE_ID, NOMBRE, EMAIL, TELEFONO, DIRECCION)
VALUES (3, 1, 'María García', 'vendedor1@inmo.test', '5552345678', 'Zona 10, Guatemala');

INSERT INTO VENDEDOR (AGENTE_ID, NOMBRE, EMAIL, TELEFONO, DIRECCION)
VALUES (1, 'Pedro Rodríguez', 'vendedor2@inmo.test', '5553456789', 'Zona 14, Guatemala');

PROMPT - Vendedores insertados

-- Compradores
INSERT INTO COMPRADOR (USUARIO_ID, AGENTE_ID, NOMBRE, APELLIDO, DIRECCION, TELEFONO, ESTADO_CIVIL, NACIONALIDAD, EDAD, EMAIL)
VALUES (4, 1, 'Carlos', 'López', 'Zona 15, Guatemala', '5554567890', 'CASADO', 'Guatemalteco', 35, 'comprador1@inmo.test');

INSERT INTO COMPRADOR (AGENTE_ID, NOMBRE, APELLIDO, DIRECCION, TELEFONO, ESTADO_CIVIL, NACIONALIDAD, EDAD, EMAIL)
VALUES (2, 'Laura', 'Fernández', 'Zona 9, Guatemala', '5555678901', 'SOLTERO', 'Guatemalteca', 28, 'comprador2@inmo.test');

INSERT INTO COMPRADOR (AGENTE_ID, NOMBRE, APELLIDO, DIRECCION, TELEFONO, ESTADO_CIVIL, NACIONALIDAD, EDAD, EMAIL)
VALUES (1, 'Roberto', 'Méndez', 'Zona 11, Guatemala', '5556789012', 'CASADO', 'Guatemalteco', 42, 'comprador3@inmo.test');

PROMPT - Compradores insertados

-- Inmuebles
INSERT INTO INMUEBLE (VENDEDOR_ID, AGENTE_ID, DIRECCION, TIPO, PRECIO, METRAJE, ANTIGUEDAD, CONDICION, HABITACIONES, BANOS, ESTACIONAMIENTOS, DESCRIPCION)
VALUES (1, 1, 'Zona 10, 5ta Avenida 12-34', 'CASA', 850000.00, 250.50, 5, 'SEMI_NUEVO', 4, 3, 2,
        'Casa amplia en zona residencial exclusiva, con jardín y áreas verdes');

INSERT INTO INMUEBLE (VENDEDOR_ID, AGENTE_ID, DIRECCION, TIPO, PRECIO, METRAJE, ANTIGUEDAD, CONDICION, HABITACIONES, BANOS, ESTACIONAMIENTOS, DESCRIPCION)
VALUES (2, 1, 'Zona 14, Torre Empresarial Piso 15', 'DEPARTAMENTO', 450000.00, 120.00, 2, 'NUEVO', 3, 2, 1,
        'Departamento moderno con vista panorámica de la ciudad');

INSERT INTO INMUEBLE (VENDEDOR_ID, AGENTE_ID, DIRECCION, TIPO, PRECIO, METRAJE, CONDICION, DESCRIPCION)
VALUES (1, 2, 'Carretera a El Salvador Km 15', 'TERRENO', 250000.00, 500.00, 'NUEVO',
        'Terreno plano ideal para desarrollo habitacional o comercial');

INSERT INTO INMUEBLE (VENDEDOR_ID, AGENTE_ID, DIRECCION, TIPO, PRECIO, METRAJE, ANTIGUEDAD, CONDICION, HABITACIONES, BANOS, ESTACIONAMIENTOS, DESCRIPCION)
VALUES (2, 2, 'Zona 16, Cayalá Boulevard', 'DEPARTAMENTO', 680000.00, 180.00, 1, 'NUEVO', 3, 3, 2,
        'Departamento de lujo en exclusivo complejo residencial');

INSERT INTO INMUEBLE (VENDEDOR_ID, AGENTE_ID, DIRECCION, TIPO, PRECIO, METRAJE, ANTIGUEDAD, MATERIAL, CONDICION, DESCRIPCION)
VALUES (1, 1, 'Zona 4, Avenida Reforma', 'LOCAL', 320000.00, 85.00, 10, 'Concreto', 'REMODELADO',
        'Local comercial en zona de alto tráfico, excelente para negocios');

PROMPT - Inmuebles insertados

-- Ofertas
INSERT INTO OFERTA (INMUEBLE_ID, COMPRADOR_ID, AGENTE_ID, MONTO, FORMA_PAGO, TIEMPO_PAGO, COMENTARIOS)
VALUES (1, 1, 1, 800000.00, 'FINANCIAMIENTO', 24, 'Interesado en la propiedad, solicito financiamiento bancario');

INSERT INTO OFERTA (INMUEBLE_ID, COMPRADOR_ID, AGENTE_ID, MONTO, FORMA_PAGO, TIEMPO_PAGO, COMENTARIOS)
VALUES (2, 2, 2, 450000.00, 'EFECTIVO', 1, 'Pago de contado, disponibilidad inmediata para cerrar trato');

INSERT INTO OFERTA (INMUEBLE_ID, COMPRADOR_ID, AGENTE_ID, MONTO, FORMA_PAGO, TIEMPO_PAGO, COMENTARIOS)
VALUES (3, 3, 1, 230000.00, 'MIXTO', 12, 'Ofrezco 50% de enganche y el resto financiado');

PROMPT - Ofertas insertadas

COMMIT;

PROMPT ============================================================================
PROMPT Datos de prueba insertados exitosamente
PROMPT ============================================================================

-- ============================================================================
-- PASO 6: VERIFICACIÓN
-- ============================================================================

PROMPT ============================================================================
PROMPT VERIFICANDO INSTALACIÓN...
PROMPT ============================================================================

SELECT 'USUARIO: ' || COUNT(*) || ' registros' AS VERIFICACION FROM USUARIO;
SELECT 'AGENTE: ' || COUNT(*) || ' registros' AS VERIFICACION FROM AGENTE;
SELECT 'VENDEDOR: ' || COUNT(*) || ' registros' AS VERIFICACION FROM VENDEDOR;
SELECT 'COMPRADOR: ' || COUNT(*) || ' registros' AS VERIFICACION FROM COMPRADOR;
SELECT 'INMUEBLE: ' || COUNT(*) || ' registros' AS VERIFICACION FROM INMUEBLE;
SELECT 'OFERTA: ' || COUNT(*) || ' registros' AS VERIFICACION FROM OFERTA;

PROMPT ============================================================================
PROMPT INSTALACIÓN COMPLETADA EXITOSAMENTE
PROMPT ============================================================================
PROMPT
PROMPT Usuario de base de datos: INMO
PROMPT Password: inmo123
PROMPT
PROMPT Usuarios de aplicación (todos con password 123456):
PROMPT - admin@inmo.test (ADMIN)
PROMPT - agente1@inmo.test (AGENTE)
PROMPT - vendedor1@inmo.test (VENDEDOR)
PROMPT - comprador1@inmo.test (COMPRADOR)
PROMPT
PROMPT Tablas creadas: 8
PROMPT Triggers creados: 11
PROMPT Datos de prueba: Sí
PROMPT
PROMPT ¡La base de datos está lista para usarse!
PROMPT ============================================================================
